### ISSUE TITLE
Where is the debug images

### ISSUE THREAD

**Issue by SpaceboyRoss01** [copy/images#2]
The website is missing some of the images and the repository is missing some of the debug images too.
Hey, Fabian please email me a zip of all of the windows images please. (spaceboyross@yandex.com)

**Comment by copy** [comment]
Unfortunately I have limited hosting space and upload speed. All Windows images are several hundreds of gigabytes in size. I can, however, tell you how to obtain them:

- Images that are used on the website can be found here: https://i.copy.sh/images/
- Windows 1 through 2000 can be found here: https://winworldpc.com/library
- Windows XP and up are obtained from legally purchased licenses
- Some newer versions can be found here: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
